### ISSUE TITLE
seventh_chord_exercise_maker, triad_exercise_maker, interval_exercise_maker don't show up in plugin manager

### ISSUE THREAD

**Issue by rpbouman** [jwmatthys/musescore-theory-plugins#7]
I followed the instructions from the read me but I don't see these in the pluginmanager:

- seventh_chord_exercise_maker
- triad_exercise_maker
- interval_exercise_maker

![image](https://user-images.githubusercontent.com/647315/104075491-357a5d00-5213-11eb-84da-1fba341dc01c.png)

![image](https://user-images.githubusercontent.com/647315/104075514-44f9a600-5213-11eb-8677-a5714935b353.png)

**Comment by jwmatthys** [comment]
Thanks. Those maker plugins need to be updated to the MuseScore3 API.

**Comment by jwmatthys** [comment]
Fixed in latest commit https://github.com/jwmatthys/musescore-theory-plugins/commit/8597b4a2ddd4b5d7b43b42e4648baf743c069735

**Comment by rpbouman** [comment]
Works for me! Thanks man! :)
